### ISSUE TITLE
c++ issues

### ISSUE THREAD

**Issue by julian-upc** [julian-upc/discrete-geometry#141]
Let's talk about some details in your c++ code.

**Comment by julian-upc** [comment]
`vector<int> Gale_Diagram::findMissing(int i, int j, int k, int l) const{
    vector<int> pointNums(points.size());
    for(int a=0; a<points.size(); a++) pointNums[a]=a;
`

**Comment by Simonvde** [comment]
That is indeed a clearer way to set it up. I hadn't heard of it before.

**Comment by julian-upc** [comment]
I opened a new pull request where I'll add comments. In the meantime, could you please upload your Makefile or whatever infrastructure you have for actually compiling the project?

I have igraph and gmpxx installed.

**Comment by Simonvde** [comment]
I ran the code in Xcode (mac c++ editor) and as such didn’t have any makefile.

To run the code I added to “other linker flags” -lgmp -lgmpxx -ligraph
Added to "library search path" /usr/local/lib/
And to "header search path” /usr/local/include/ /usr/local/include/igraph

I hope this is sufficient.
